services:
  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    restart: unless-stopped

    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "10000-20000:10000-20000/udp"

    volumes:
      - ./asterisk/etc:/etc/asterisk
      - ./asterisk/lib:/var/lib/asterisk
      - ./asterisk/log:/var/log/asterisk
      - ./asterisk/spool:/var/spool/asterisk

    environment:
      - TZ=America/Fortaleza

