services:
  asterisk:
    image: andrius/asterisk
    container_name: asterisk
    ports:
      - "5060:5060/udp"
      - "5038:5038"
    volumes:
      - ./asterisk:/etc/asterisk
      - ./asterisk/logs:/var/log/asterisk

  logviewer:
    build: ./logviewer
    container_name: asterisk-log-viewer
    ports:
      - "8080:8080"
    volumes:
      - ./asterisk/logs:/var/log/asterisk:ro
    depends_on:
      - asterisk
