[general]
static=yes
writeprotect=no
clearglobalvars=no

[internal]
; Chamada entre ramais
exten => 1000,1,NoOp(Call to 1000)
 same => n,Dial(SIP/1000,20)
 same => n,Hangup()

exten => 1001,1,NoOp(Call to 1001)
 same => n,Dial(SIP/1001,20)
 same => n,Hangup()

; Teste de IVR / áudio
exten => 2000,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()

; Teste de voicemail fake
exten => 3000,1,Answer()
 same => n,Playback(vm-goodbye)
 same => n,Hangup()
