[internal]
exten => 1000,1,NoOp(Call to 1000)
 same => n,Dial(PJSIP/1000)
 same => n,Hangup()

exten => 1001,1,NoOp(Call to 1001)
 same => n,Dial(PJSIP/1001)
 same => n,Hangup()

exten => 2000,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()
