[general]
context=default
allowoverlap=no
udpbindaddr=0.0.0.0
tcpenable=no
transport=udp
language=pt_BR
disallow=all
allow=ulaw
allow=alaw

; ===== Ramais =====

[1000]
type=friend
secret=1000
host=dynamic
context=internal
nat=no
canreinvite=no
qualify=yes

[1001]
type=friend
secret=1001
host=dynamic
context=internal
nat=no
canreinvite=no
qualify=yes
