[geral]

[3000]
type=bridge
max_members=50

[roip_user]
type=user
music_on_hold_when_empty=no
quiet=yes

[roip_menu]
type=menu

[3000_user]
type=user
template=roip_user
talk_detection_events=yes

[3000_menu]
type=menu
