;==========================
; Perfis de Bridge
;==========================

[roip_bridge]
type=bridge
max_members=50
mixing_interval=10
record_conference=no

;==========================
; Perfis de Usuario
;==========================

[roip_user]
type=user
admin=no
marked=no
startmuted=yes
music_on_hold_when_empty=no
quiet=yes

[roip_admin]
type=user
admin=yes
startmuted=no
;===========================
; Perfis de Menu
;===========================

[roip_menu]
type=menu
*1=exec:ptt_request,s,1
*0=exec:ptt_release,s,1
*9=leave_conference
