[general]
static=yes
writeprotect=no

[roip]
exten => _00XX,1,NoOp(Chamada interna para ${EXTEN})
   same => n,Dial(PJSIP/${EXTEN},30)
   same => n,Hangup()

;======================================
; Grupo geral - 1000
;======================================
exten => 1000,1,NoOp(Entrando no Grupo geral - 1000 - RoIP)

   same => n,ConfBridge(ROIP_00,roip_bridge,roip_user,roip_menu)
   same => n,Hangup()

;===================================
; Grupo geral - 1010
;===================================
exten => 1010,1,NoOp(Entrando no Grupo geral - 1010 - RoIP)

   same => n,ConfBridge(ROIP_01,roip_bridge,roip_user,roip_menu)
   same => n,Hangup()

;===================================
; Subrotinas de PTT
;===================================
[ptt_request]
exten => s,1,NoOp(PTT request de ${CALLERID(num)} no grupo ${CONFBRIDGE(bridge,uniqueid)})
   ; Setando variaveis de ambiente
   same => n,Set(GROUP_ID=${CONFBRIDGE(bridge,uniqueid)})
   same => n,Set(LOCK_KEY=ROIP_${GROUP_ID}_LOCK)
   same => n,Set(QUEUE_ID=roip_queue_${GROUP_ID})

   same => n,AGI(roip_log.agi,request,${GROUP_ID},${CALLERID(num)})

   ;
   same => n,Set(IS_BUSY=${DB_EXISTS(${LOCK_KEY})})
   same => n,GotoIf($["${IS_BUSY}"="1"]?busy:grant)

   same => n(grant),NoOp(Fala concedida)
   same => n,Set(DB(${LOCK_KEY})=${CALLERID(num)})
   same => n,Set(CONFBRIDGE(user,muted)=no)
   same => n,AGI(roip.agi,grant,${GROUP_ID},${CALLERID(num)})
   same => n,Return()

   same => n(busy),NoOp(Canal do grupo ocupado, entrando na Queue ${QUEUE_ID})
   same => n,AGI(roip.agi,enqueue,${GROUP_ID},${CALLERID(num)})
   same => n,Queue(${QUEUE_ID},t)
   same => n,Return()

[ptt_release]
exten => s,1,NoOp(PTT release de ${CALLERID(num)})
   same => n,Set(GROUP_ID=${CONFBRIDGE(bridge,uniqueid)})
   same => n,Set(QUEUE_ID=roip_queue_${GROUP_ID})
   same => n,Set(LOCK_KEY=ROIP_${GROUP_ID}_LOCK)

   same => n,GotoIf($["DB(${LOCK_KEY})"="${CALLERID(num)}"]?ok:deny)
   same => n(ok),AGI(roip.agi,release,${GROUP_ID},${CALLERID(num)})

   same => n,DBDel(${LOCK_KEY})
   same => n,Set(CONFBRIDGE(user,muted)=yes)

   same => n,NoOp(Verificando fila ${QUEUE_ID})
   same => n,Queue(${QUEUE_ID},t)
   same => n(deny),NoOp(${CALLERID(num)} tentou liberar sem posse)
   same => n,Return()
