[general]
static=yes
writeprotect=no

[roip]

; ==============================
; Chamadas diretas entre ramais
; ==============================
exten => _00XX,1,NoOp(Chamada interna para ${EXTEN})
   same => n,Dial(PJSIP/${EXTEN},30)
   same => n,Hangup()

; ======================================
; Grupo geral - 1000 (ROIP_00)
; ======================================
exten => 1000,1,NoOp(Entrando no Grupo geral - 1000 - RoIP)
   same => n,Set(GROUP_ID=ROIP_00)              ; ID lógico do grupo
   same => n,Set(SESSION_ID=${UNIQUEID})

   ; entrada do usuário
   same => n,AGI(roip_logger.agi,join,${GROUP_ID},${CALLERID(num)},${SESSION_ID})
   ; Fail-safe
   same => n,Set(CHANNEL(hangup_handler_push)=roip-hangup,s,1(${GROUP_ID},${CALLERID(num)},${SESSION_ID}))
   
   same => n,ConfBridge(${GROUP_ID},roip_bridge,roip_user,roip_menu)
   same => n,Hangup()

; ======================================
; Grupo geral - 1010 (ROIP_01)
; ======================================
exten => 1010,1,NoOp(Entrando no Grupo geral - 1010 - RoIP)
   same => n,Set(GROUP_ID=ROIP_01)              ; ID lógico do grupo
   same => n,Set(SESSION_ID=${UNIQUEID})

   ; entrada do usuário
   same => n,AGI(roip_logger.agi,join,${GROUP_ID},${CALLERID(num)},${SESSION_ID})
   ; Fail-safe
   same => n,Set(CHANNEL(hangup_handler_push)=roip-hangup,s,1(${GROUP_ID},${CALLERID(num)},${SESSION_ID}))

   same => n,ConfBridge(${GROUP_ID},roip_bridge,roip_user,roip_menu)
   same => n,Hangup()

; ======================================
; Hangup Handler
; ======================================
[roip-hangup]
exten => s,1,AGI(roip_logger.agi,hangup,${ARG1},${ARG2},${ARG3})
   same => n,Return()