[general]
autofill=yes
shared_lastcall=yes
updatecdr=yes

;================
; Grupo 00
;================
[roip_queue_00]
eventwhencalled=yes
strategy=ringall
timeout=5
retry=1
wrapuptime=0
maxlen=50
joinempty=yes
leavewhenempty=no
autofill=no
ringinuse=no
reportholdtime=no
memberdelay=0
weight=0

;================
; Grupo 01
;================
[roip_queue_01]
eventwhencalled=yes
strategy=ringall
timeout=5
retry=1
wrapuptime=0
maxlen=50
joinempty=yes
leavewhenempty=no
autofill=no
ringinuse=no
reportholdtime=no
memberdelay=0
weight=0
